# clean census data

In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
csv_path = os.path.join('..', '..', 'raw', 'census', 'income_by_zip', 'ACS_16_5YR_S1901_with_ann.csv')
df = pd.read_csv(csv_path)
df.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_EST_VC01,HC01_MOE_VC01,HC01_EST_VC02,HC01_MOE_VC02,HC01_EST_VC03,HC01_MOE_VC03,HC01_EST_VC04,...,HC01_EST_VC13,HC01_MOE_VC13,HC01_EST_VC15,HC01_MOE_VC15,HC01_EST_VC18,HC01_MOE_VC18,HC01_EST_VC19,HC01_MOE_VC19,HC01_EST_VC20,HC01_MOE_VC20
0,Id,Id2,Geography,Households; Estimate; Total,Households; Margin of Error; Total,"Households; Estimate; Less than $10,000","Households; Margin of Error; Less than $10,000","Households; Estimate; $10,000 to $14,999","Households; Margin of Error; $10,000 to $14,999","Households; Estimate; $15,000 to $24,999",...,Households; Estimate; Median income (dollars),Households; Margin of Error; Median income (do...,Households; Estimate; Mean income (dollars),Households; Margin of Error; Mean income (doll...,Households; Estimate; PERCENT ALLOCATED - Hous...,Households; Margin of Error; PERCENT ALLOCATED...,Households; Estimate; PERCENT ALLOCATED - Fami...,Households; Margin of Error; PERCENT ALLOCATED...,Households; Estimate; PERCENT ALLOCATED - Nonf...,Households; Margin of Error; PERCENT ALLOCATED...
1,8600000US91911,91911,ZCTA5 91911,24309,646,5.2,1.1,6.2,1.1,11.1,...,51383,1874,62932,2137,43.2,(X),(X),(X),(X),(X)
2,8600000US91914,91914,ZCTA5 91914,4582,205,1.3,1.2,1.3,1.2,3.4,...,124578,7047,137640,8680,32.2,(X),(X),(X),(X),(X)
3,8600000US91915,91915,ZCTA5 91915,7993,256,2.0,1.3,1.7,1.8,3.2,...,104170,6753,111918,8589,28.0,(X),(X),(X),(X),(X)
4,8600000US91932,91932,ZCTA5 91932,9044,295,6.4,1.7,7.1,2.0,9.4,...,48010,1975,59870,2942,28.2,(X),(X),(X),(X),(X)

In [3]:
df.rename(columns=df.loc[0], inplace=True)
df.drop(0, inplace=True)
df.set_index('Id2', inplace=True)
df.index.name = 'zip_code'
df.head()

,Id,Geography,Households; Estimate; Total,Households; Margin of Error; Total,"Households; Estimate; Less than $10,000","Households; Margin of Error; Less than $10,000","Households; Estimate; $10,000 to $14,999","Households; Margin of Error; $10,000 to $14,999","Households; Estimate; $15,000 to $24,999","Households; Margin of Error; $15,000 to $24,999",...,Households; Estimate; Median income (dollars),Households; Margin of Error; Median income (dollars),Households; Estimate; Mean income (dollars),Households; Margin of Error; Mean income (dollars),Households; Estimate; PERCENT ALLOCATED - Household income in the past 12 months,Households; Margin of Error; PERCENT ALLOCATED - Household income in the past 12 months,Households; Estimate; PERCENT ALLOCATED - Family income in the past 12 months,Households; Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months,Households; Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Households; Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months
zip_code,,,,,,,,,,,,,,,,,,,,,
91911,8600000US91911,ZCTA5 91911,24309,646,5.2,1.1,6.2,1.1,11.1,1.2,...,51383,1874,62932,2137,43.2,(X),(X),(X),(X),(X)
91914,8600000US91914,ZCTA5 91914,4582,205,1.3,1.2,1.3,1.2,3.4,1.9,...,124578,7047,137640,8680,32.2,(X),(X),(X),(X),(X)
91915,8600000US91915,ZCTA5 91915,7993,256,2.0,1.3,1.7,1.8,3.2,1.8,...,104170,6753,111918,8589,28.0,(X),(X),(X),(X),(X)
91932,8600000US91932,ZCTA5 91932,9044,295,6.4,1.7,7.1,2.0,9.4,1.9,...,48010,1975,59870,2942,28.2,(X),(X),(X),(X),(X)
91942,8600000US91942,ZCTA5 91942,16700,458,4.0,1.2,7.0,1.5,9.0,1.5,...,55753,3194,70677,3837,28.6,(X),(X),(X),(X),(X)

In [4]:
df.columns

Index(['Id', 'Geography', 'Households; Estimate; Total',
       'Households; Margin of Error; Total',
       'Households; Estimate; Less than $10,000',
       'Households; Margin of Error; Less than $10,000',
       'Households; Estimate; $10,000 to $14,999',
       'Households; Margin of Error; $10,000 to $14,999',
       'Households; Estimate; $15,000 to $24,999',
       'Households; Margin of Error; $15,000 to $24,999',
       'Households; Estimate; $25,000 to $34,999',
       'Households; Margin of Error; $25,000 to $34,999',
       'Households; Estimate; $35,000 to $49,999',
       'Households; Margin of Error; $35,000 to $49,999',
       'Households; Estimate; $50,000 to $74,999',
       'Households; Margin of Error; $50,000 to $74,999',
       'Households; Estimate; $75,000 to $99,999',
       'Households; Margin of Error; $75,000 to $99,999',
       'Households; Estimate; $100,000 to $149,999',
       'Households; Margin of Error; $100,000 to $149,999',
       'Households; Estimate; $150,000 to $199,999',
       'Households; Margin of Error; $150,000 to $199,999',
       'Households; Estimate; $200,000 or more',
       'Households; Margin of Error; $200,000 or more',
       'Households; Estimate; Median income (dollars)',
       'Households; Margin of Error; Median income (dollars)',
       'Households; Estimate; Mean income (dollars)',
       'Households; Margin of Error; Mean income (dollars)',
       'Households; Estimate; PERCENT ALLOCATED - Household income in the past 12 months',
       'Households; Margin of Error; PERCENT ALLOCATED - Household income in the past 12 months',
       'Households; Estimate; PERCENT ALLOCATED - Family income in the past 12 months',
       'Households; Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months',
       'Households; Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months',
       'Households; Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months'],
      dtype='object')

In [5]:
mean = df.filter(like='Mean')
median = df.filter(like='Median')
mean_med = mean.merge(median, left_index=True, right_index=True)
mean_med.columns

Index(['Households; Estimate; Mean income (dollars)',
       'Households; Margin of Error; Mean income (dollars)',
       'Households; Estimate; Median income (dollars)',
       'Households; Margin of Error; Median income (dollars)'],
      dtype='object')

In [6]:
mean_med.columns = mean_med.columns.map(lambda x: re.sub('Households; |Estimate; | \(dollars\)', '', x))
mean_med.columns = mean_med.columns.map(lambda x: re.sub('Margin of Error;', 'MoE', x))
mean_med.head()

         Mean income MoE Mean income Median income MoE Median income
zip_code
91911          62932            2137         51383              1874
91914         137640            8680        124578              7047
91915         111918            8589        104170              6753
91932          59870            2942         48010              1975
91942          70677            3837         55753              3194

In [7]:
mean_med.replace(to_replace='-', value=np.NaN, inplace=True)
mean_med.replace(to_replace='N', value=np.NaN, inplace=True)
mean_med.replace(to_replace='**', value=np.NaN, inplace=True)
mean_med.dropna(inplace=True)

In [8]:
mean_path = os.path.join('..', '..', 'data', 'census_income_by_zip.csv')
mean_med.to_csv(mean_path)